remote_theme: pages-themes/minimal@v0.2.0
logo: "https://avatars.githubusercontent.com/u/63933270?v=4"
title: "Gabriel's Data Analyst Portfolio"
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one